### ISSUE TITLE
Text not showing up

### ISSUE THREAD

**Issue by joroad** [HandyOrg/HandyWinGet#19]
All of the text in the name column is not showing up as well as some publisher text. I also can not see text in the available version dropdowns. See attached screenshot for more info. 

![Screenshot](https://user-images.githubusercontent.com/43655781/113361874-ff80dc80-931a-11eb-9935-3b0e08dc0907.jpg)

**Comment by JohnLGalt** [comment]
This is also not occurring here.  Same questions - has it always happened or did it just start?

How much RAM do you ahve nad what is your page file size (I ask because it seems like it is running out of resources to display everything, but it may be something else)

**Comment by ghost1372** [comment]
This problem is due to a defect in the manifest parsing I will solve this problem soon

**Comment by ghost1372** [comment]
I finally found the problem: **Microsoft** 😁
They arranged the manifests alphabetically in the folder.
https://github.com/microsoft/winget-pkgs/tree/master/manifests

**Comment by JohnLGalt** [comment]
@ghost1372 - could it be not affecting me because of the overkill RAM I have installed (128 GB)?

Or is this one of those things that manifests itself occasionally and sporadically and will go away once you've fixed the code?

**Comment by ghost1372** [comment]
@JohnLGalt  No Because you are using old manifests If you refresh, you will have the same problem.
The problem is that Microsoft has changed the structure of the [manifest](https://github.com/microsoft/winget-cli/blob/master/doc/ManifestSpecv1.0.md), so HandyWinget can not identify the new structure.
I am currently working on a new version

**Comment by ghost1372** [comment]
@joroad please try new [version](https://github.com/HandyOrg/HandyWinGet/releases/tag/v3.2.0.0)

**Comment by JohnLGalt** [comment]
I'm now getting similar issues to Joroad on both 3.0.2.0 and 3.2.0.0

**Comment by ghost1372** [comment]
> I'm now getting similar issues to Joroad on both 3.0.2.0 and 3.2.0.0
> 
> for new 3.2.0.0 I downloaded portable, not setup.

Did you refresh it?
Delete this folder and try again

`C:\Users\{Your Username}\AppData\Roaming/HandyWinget`
I will release a new version soon that will automatically delete the old manifest sorry for that

**Comment by ghost1372** [comment]
try new version
https://github.com/HandyOrg/HandyWinGet/releases/tag/v3.2.1.0

**Comment by JohnLGalt** [comment]
OK, new version is showing packages again.  However, new version will not show installed packages, even version that 3.0.2.0 would show as installed.  I've tried both internal and winget-cli method.

I'm going to run older version side by side and see if I can figure out what it is going on.

**Comment by JohnLGalt** [comment]
I checked the 3 versions I have - 3.0.2.0, 3.2.0.0 and 3.2.1.0/

I verified the below results by deleting data in both \AppData\Local\HandyWinGet and \AppData\Roaming\HandyWinGet before running each version.

3.0.2.0 - not items shown at all.  That is understandable as you mentioned elsewhere support for a new manifest form.   Not an issue.

3.2.0.0 - manifests load fine now (but were not loading earlier, even after refreshing).  But app cannot detect installed programs.

3.2.1.0 - manifests load fine now.  But app cannot detect installed programs.

I can still provide ss, if you want, but no point since behavior is identical in both  3.2.0.0 and 3.2.1.0.

**Comment by ghost1372** [comment]
Thank you @JohnLGalt 
Please try the [new version 3.2.2.0](https://github.com/HandyOrg/HandyWinGet/releases/tag/v3.2.2.0) I hastily released a new version last night and did not have enough time to test😅
I fixed installed packages issue, now it should work again as before
also I checked the package you said, we read the information directly from the manifest and The package you mentioned has the same information as the information in the handywinget.
So you need to follow this from the [Microsoft repository](https://github.com/microsoft/winget-pkgs)

![Untitled](https://user-images.githubusercontent.com/9213496/113506641-48bf6f00-955b-11eb-84f6-50613bc8e061.png)

**Comment by JohnLGalt** [comment]
Yeah, after I posted my comment, I, too, used PS to verify version in WinGet database - it is indeed incorrect there, so nothing you can actually do about it.

I understand that.

I'll try the new version in a few minutes and report back.

**Comment by JohnLGalt** [comment]
Version 3.2.2.0 is showing installed applications correctly again.  Manual refresh no longer breaks viewing of package info.

Some of the information is not correct, but I suspect that, again, this is due to the information being supplied by the WinGet repository, and not anything that HWG is doing incorrectly.

Posting potential RFF in new post.  This looks finally closed.  Thanks for all your hard work on this!
